version: '3.8'

services:
  dev:
    build:
      context: .
      target: development
    container_name: rowo_oekostrom_db_dev
    volumes:
      - type: bind
        source: ./oekostrom_db
        target: /home/app/oekostrom_db
    env_file:
      - .env
    environment:
      # ensure we can connect to
      DJANGO_INTERFACE: "0.0.0.0:8000"
      DJANGO_ALLOWED_HOSTS: "*"
    depends_on:
      - db
    ports:
      - "8000:8000"

#  prod:
#    build:
#      context: .
#      target: production
#    container_name: rowo_oekostrom_db_prod
#    env_file:
#      - .env
#    depends_on:
#      - db
#    ports:
#      - "8000:8000"

  db:
    image: postgres:13
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    container_name: rowo_oekostrom_db_postgres
    env_file:
      - .env
#    volumes:
#      - type: bind
#        source: ./.db
#        target: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
