version: '3.8'

services:
  dev:
    build:
      context: .
      target: development
    container_name: rowo_oekostrom_db_dev
    volumes:
      - type: bind
        source: ./oekostrom_db
        target: /home/app/oekostrom_db
    env_file:
      - .env
    environment:
      # ensure we can connect to
      DJANGO_INTERFACE: "0.0.0.0:8000"
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 dev"
      DJANGO_CSRF_TRUSTED_ORIGINS: "http://127.0.0.1 http://127.0.0.1:8000"
    depends_on:
      - db
    ports:
      - "8000:8000"

  nginx_dev:
    build:
      context: .
      target: nginx
    container_name: rowo_oekostrom_db_nginx_dev
    environment:
      NGINX_HOST: "foobar.com"
      NGINX_PORT: "80"
      NGINX_TARGET: "dev:8000"
    ports:
      - "80:80"
    depends_on:
      - dev

  db:
    image: postgres:13
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    container_name: rowo_oekostrom_db_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
