[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "UP",
    "I",
    "DJ",
    "Q",
    "RET",
    "TCH",
    "ARG",
    "PTH",
    "PL",
]

[tool.ruff.format]
line-ending = "lf"

[tool.ruff.lint.pycodestyle]
max-line-length = 120