# Generated by Django 5.0.7 on 2024-08-05 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anbieter", "0003_init_data_2024"),
    ]

    operations = [
        migrations.AddField(
            model_name="anbieter",
            name="mutter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="anbieter.anbieter",
                verbose_name="Mutter Firma",
            ),
        ),
        migrations.AddField(
            model_name="anbieter",
            name="north_data",
            field=models.URLField(
                blank=True,
                db_default="",
                max_length=1024,
                verbose_name="North Data Profil",
            ),
        ),
        migrations.AddField(
            model_name="anbieter",
            name="wikipedia",
            field=models.URLField(
                blank=True,
                db_default="",
                max_length=1024,
                verbose_name="Wikipedia Eintrag",
            ),
        ),
        migrations.AlterField(
            model_name="anbieter",
            name="oekotest",
            field=models.OneToOneField(
                blank=True,
                db_default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="anbieter.oekotest",
            ),
        ),
        migrations.AlterField(
            model_name="anbieter",
            name="ok_power",
            field=models.OneToOneField(
                blank=True,
                db_default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="anbieter.okpower",
            ),
        ),
        migrations.AlterField(
            model_name="anbieter",
            name="rowo_2019",
            field=models.OneToOneField(
                blank=True,
                db_default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="anbieter.rowo2019",
            ),
        ),
        migrations.AlterField(
            model_name="anbieter",
            name="stromauskunft",
            field=models.OneToOneField(
                blank=True,
                db_default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="anbieter.stromauskunft",
            ),
        ),
        migrations.AlterField(
            model_name="anbieter",
            name="verivox",
            field=models.OneToOneField(
                blank=True,
                db_default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="anbieter.verivox",
            ),
        ),
    ]
