# Generated by Django 5.1rc1 on 2024-08-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anbieter", "0005_combine_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="anbieter",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "0 - Nicht geprüft"),
                    (4, "4 - Existenz geprüft"),
                    (8, "8 - Ökostrom geprüft"),
                    (16, "16 - Ökostrom Anteil geprüft"),
                    (32, "32 - EE Anteil geprüft"),
                    (64, "64 - Zusätzlichkeit geprüft"),
                    (128, "128 - Unabhängigkeit geprüft "),
                    (256, "256 - Kein Geld Atom/Kohl geprüft"),
                    (512, "512 - Fragebogen versendet"),
                    (1024, "1024 - Fragebogen zurück erhalten"),
                    (2048, "2048 - Fragebogen eingearbeitet"),
                    (4096, "4096 - Prüfung beendet"),
                ],
                db_default=0,
            ),
        ),
    ]
