# Generated by Django 5.1 on 2024-08-09 22:15

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anbieter", "0007_fix_and_fill_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="anbieter",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="anbieter",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                null=True,
            ),
        ),
    ]
