# Generated by Django 5.1 on 2024-08-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anbieter", "0008_anbieter_created_at_anbieter_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="anbieter",
            name="german_wide",
            field=models.BooleanField(
                db_default=True,
                help_text="Deutschlandweiter Anbieter",
                verbose_name="🇩🇪",
            ),
        ),
    ]
