# Generated by Django 5.1 on 2024-10-04 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anbieter", "0009_anbieter_german_wide"),
    ]

    operations = [
        migrations.AddField(
            model_name="anbieter",
            name="begruendung_extern",
            field=models.TextField(
                blank=True,
                help_text="Zusatzbegründung für Bewertung für Homepage",
                verbose_name="Begründung für Homepage",
            ),
        ),
        migrations.AddField(
            model_name="anbieter",
            name="sells_from",
            field=models.ForeignKey(
                blank=True,
                db_default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sellers",
                to="anbieter.anbieter",
                verbose_name="Verkauft Strom von",
            ),
        ),
        migrations.AlterField(
            model_name="anbieter",
            name="begruendung",
            field=models.TextField(
                blank=True,
                help_text="Interne Begründung/Notizen zum Anbieter und deren Bewertung",
                verbose_name="Notiz/Begründung Intern",
            ),
        ),
        migrations.AlterField(
            model_name="anbieter",
            name="mutter",
            field=models.ForeignKey(
                blank=True,
                db_default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="anbieter.anbieter",
                verbose_name="Mutter Firma",
            ),
        ),
    ]
