# Generated by Django 5.1.2 on 2024-10-09 19:30

from django.db import migrations, models
from django.utils.text import slugify


def populate_slug(apps, schema_editor):  # noqa: ARG001
    Anbieter = apps.get_model("anbieter", "Anbieter")
    for anbieter in Anbieter.objects.all():
        anbieter.slug_id = slugify(anbieter.name)
        anbieter.save()


class Migration(migrations.Migration):
    dependencies = [
        ("anbieter", "0011_template_alter_anbietername_anbieter"),
    ]

    operations = [
        migrations.AddField(
            model_name="anbieter",
            name="slug_id",
            field=models.SlugField(default=None, null=True, max_length=255),
        ),
        migrations.RunPython(populate_slug),
    ]
