# Generated by Django 5.1.2 on 2024-10-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anbieter", "0012_anbieter_add_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anbieter",
            name="slug_id",
            field=models.SlugField(default=None, unique=True, max_length=255),
        ),
    ]
