# Generated by Django 5.1.2 on 2024-10-26 18:13

from django.db import migrations

import anbieter.field_helper
import anbieter.fields


class Migration(migrations.Migration):
    dependencies = [
        ("anbieter", "0017_alter_companysurvey2024_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companysurvey2024",
            name="power_plants_file",
            field=anbieter.fields.FileField(
                blank=True,
                help_text="Bitte laden Sie die Tabelle hoch.",
                upload_to=anbieter.field_helper.upload_to_power_plants,
                verbose_name="Erzeugungsanlagen Tabelle",
            ),
        ),
    ]
