# Generated by Django 5.1.2 on 2024-10-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anbieter", "0018_alter_companysurvey2024_power_plants_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="UmfrageVersendung2024",
            fields=[
                (
                    "anbieter",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="anbieter.anbieter",
                    ),
                ),
                ("sent_date", models.DateTimeField(blank=True, null=True)),
                (
                    "mail_status",
                    models.BooleanField(
                        blank=True,
                        choices=[
                            (True, "Erfüllt"),
                            (False, "Nicht erfüllt"),
                            (None, "?"),
                        ],
                        db_default=None,
                        help_text="Status des Mail versand",
                        null=True,
                        verbose_name="📧",
                    ),
                ),
                (
                    "mail_details",
                    models.TextField(help_text="i.e. Fehlermeldung aus Mail Versand"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("anbieter.anbieter",),
        ),
        migrations.AlterField(
            model_name="surveyaccess",
            name="anbieter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_access",
                to="anbieter.anbieter",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="name",
            field=models.CharField(
                choices=[
                    ("HP_EXPORT", "Homepage Text"),
                    ("SURVEY_2024_SUBJECT", "Umfrage 2024 Betreff"),
                    ("SURVEY_2024_TXT", "Umfrage 2024 Text"),
                    ("SURVEY_2024_HTML", "Umfrage 2024 Html"),
                ],
                max_length=64,
                unique=True,
            ),
        ),
    ]
