# ruff: noqa
# Generated by Django 5.1.2 on 2024-10-27 12:34

from django.db import migrations

from anbieter.models import TemplateNames


def add_templates(apps, schema_editor):  # noqa: ARG001
    Template = apps.get_model("anbieter", "Template")

    Template(
        name=TemplateNames.SURVEY2024_SUBJECT,
        template="RobinWood Ökostromreport 2024 - Datenanfrage",
    ).save()

    Template(
        name=TemplateNames.SURVEY2024_TXT,
        template="""Sehr geehrte Damen und Herren,

in diesem Jahr aktualisieren wir gerade unseren Robin Wood Ökostromreport (https://www.robinwood.de/oekostrom-report-reloaded).
Von  {{ obj.active_count }} Anbietern erfüllen Sie die Grundbedingungen 100% Ökostrom und keine offensichtlichen Verflechtungen mit Konzernen die mit Atomtechnologien oder fossilen Brennstoffen handeln.
Damit wir die Anbieter empfehlen können, welche die Energiewende am stärksten voran bringen, also vielleicht auch sie, benötigen wir aber noch ein paar Informationen von Ihnen.

Rufen Sie dazu bitte folgendes Online Formular auf:

https://stromdb.robinwood.de/survey/{{ obj.code_2024 }}

Der Link enthält einen Token, der sie berechtigt das Formular für *{{ obj.name }}* zu ändern. Teilen Sie diesen (bzw. diese Mail) daher nur mit Personen die dazu berechtigt sein sollen.
Bitte füllen Sie das Online Formular bis spätestens **30.11.2024** aus.

Rückmeldungen danach werden nicht berücksichtigt.
Nach Sichtung aller Rückmeldungen entscheiden wir ob eventuell weitere Kriterien zur Auswahl der besten Ökostromanbieter benötigt werden.

Mit freundlichen Grüßen,

Florian Kubitz""",
    ).save()

    Template(
        name=TemplateNames.SURVEY2024_HTML,
        template="""<p>Sehr geehrte Damen und Herren,<br />
<br />
in diesem Jahr aktualisieren wir gerade unseren <a href="https://www.robinwood.de/oekostrom-report-reloaded">Robin Wood Ökostromreport</a>.<br />
Von {{ obj.active_count }} Anbietern erfüllen Sie die Grundbedingungen 100% Ökostrom und keine offensichtlichen Verflechtungen mit Konzernen die mit Atomtechnologien oder fossilen Brennstoffen handeln. <br />
Damit wir die Anbieter empfehlen können, welche die Energiewende am stärksten voran bringen, also vielleicht auch sie, benötigen wir aber noch ein paar Informationen von Ihnen. <br />
Rufen Sie dazu bitte folgendes Online Formular auf:<br />
<br />
<strong><a href="https://stromdb.robinwood.de/survey/{{ obj.code_2024 }}">https://stromdb.robinwood.de/survey/{{ obj.code_2024 }}</a> <br /></strong>
<br />
Der Link enthält einen Token, der sie berechtigt das Formular für <cite>{{ obj.name }}</cite> zu ändern. Teilen Sie diesen (bzw. diese Mail) daher nur mit Personen die dazu berechtigt sein sollen. <br />
<br />
Bitte füllen Sie das Online Formular bis spätestens <strong>30.11.2024</strong> aus.<br />
Rückmeldungen danach werden nicht berücksichtigt. <br />
Nach Sichtung aller Rückmeldungen entscheiden wir ob eventuell weitere Kriterien zur Auswahl der besten Ökostromanbieter benötigt werden. <br />
<br />
Mit freundlichen Grüßen,<br />
<br />
Florian Kubitz</p>""",
    ).save()


class Migration(migrations.Migration):
    dependencies = [
        ("anbieter", "0019_add_mail"),
    ]

    operations = [migrations.RunPython(add_templates)]
