# Generated by Django 5.1.2 on 2024-10-27 14:34

from django.db import migrations


def fill_survey(apps, schema_editor):  # noqa: ARG001
    Anbieter = apps.get_model("anbieter", "Anbieter")
    for obj in Anbieter.objects.all():
        for survey in obj.companysurvey2024_set.all():
            survey.street = obj.street
            survey.city = obj.city
            survey.phone = obj.phone
            survey.fax = obj.fax
            survey.mail = obj.mail
            survey.homepage = obj.homepage
            survey.save()


class Migration(migrations.Migration):
    dependencies = [
        ("anbieter", "0020_add_mail_templates"),
    ]

    operations = [migrations.RunPython(fill_survey)]
