# Generated by Django 5.1.2 on 2024-10-29 07:10

from django.db import migrations, models

from anbieter.field_helper import get_fill_status


def calculate_fill_status(apps, schema_editor):  # noqa: ARG001
    CompanySurvey2024 = apps.get_model("anbieter", "CompanySurvey2024")
    for obj in CompanySurvey2024.objects.all():
        obj._fill_status = get_fill_status(obj.__dict__)
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("anbieter", "0022_update_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysurvey2024",
            name="_fill_status",
            field=models.DecimalField(
                db_column="filled",
                decimal_places=1,
                default=0,
                help_text="Percentage of field",
                max_digits=6,
                verbose_name="Filled",
                editable=False,
            ),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="umfrageversendung2024",
            options={
                "verbose_name": "Umfrage Mailversand Anbieter",
                "verbose_name_plural": "Umfrage: Mailversand",
            },
        ),
        migrations.RunPython(calculate_fill_status),
    ]
