# Generated by Django 5.1.2 on 2024-10-29 07:10

from django.db import migrations, models


def calculate_fill_status(apps, schema_editor):  # noqa: ARG001
    CompanySurvey2024 = apps.get_model("anbieter", "CompanySurvey2024")
    for obj in CompanySurvey2024.objects.all():
        fields = {f for f in obj.__dict__ if not f.startswith("_")}
        fields -= {
            "id",
            "created",
            "anbieter_id",
            "revision",
            "name",
            "mail",
            "homepage",
        }
        filled = sum(bool(getattr(obj, f)) for f in fields)
        obj._fill_status = filled / len(fields) * 100
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("anbieter", "0022_update_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysurvey2024",
            name="_fill_status",
            field=models.DecimalField(
                db_column="filled",
                decimal_places=1,
                default=0,
                help_text="Percentage of field",
                max_digits=6,
                verbose_name="Filled",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="umfrageversendung2024",
            options={
                "verbose_name": "Umfrage Mailversand Anbieter",
                "verbose_name_plural": "Umfrage: Mailversand",
            },
        ),
        migrations.RunPython(calculate_fill_status),
    ]
