# Generated by Django 5.1.2 on 2024-10-29 07:10

from django.db import migrations

from anbieter.field_helper import get_fill_status


def calculate_fill_status(apps, schema_editor):  # noqa: ARG001
    CompanySurvey2024 = apps.get_model("anbieter", "CompanySurvey2024")
    for obj in CompanySurvey2024.objects.all():
        obj._fill_status = get_fill_status(obj.__dict__)
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("anbieter", "0023_add_fill_status"),
    ]

    operations = [
        migrations.RunPython(calculate_fill_status),
    ]
